Repository oncokb/oncokb, pull requests merged in 2018-06, with the labels that each got.

#1082 Add new/old content in review mode for "Tumor Type"
  web/yo/app/scripts/controllers/gene.js
  web/yo/app/views/gene.html
Labels: ready to review

#1088 Mutation and Therapy Name editable
  web/yo/app/styles/main.scss
  web/yo/app/views/realtimeString.html
Labels: ready to review

#1094 Set rootScope.me first
  web/yo/app/scripts/services/user.js
Labels: ready to review

#1100 add tumor type summary count info in the mutation header
  web/yo/app/scripts/controllers/gene.js
Labels: curation interface, ready to review

#1104 remove TI general summary
  web/yo/app/views/gene.html
Labels: curation interface

#1112 Set iso form and gene type when create new genes
  web/yo/app/scripts/controllers/genes.js
  web/yo/app/scripts/services/databaseconnector.js
  web/yo/app/scripts/services/mainutils.js
Labels: ready to review

#1120 Fix display issue
  web/yo/app/scripts/controllers/gene.js
  web/yo/app/scripts/directives/realtimestring.js
  web/yo/app/styles/main.scss
  web/yo/app/views/gene.html
  web/yo/app/views/realtimeString.html
  web/yo/app/views/tools.html
Labels: ready to review

#1122 add level 4 propagation and an option to query TTS+drugs reviewed data
  web/yo/app/scripts/controllers/reportgenerator.js
  web/yo/app/scripts/directives/driverealtimestring.js
Labels: curation interface, ready to review
