Repository oncokb/oncokb, pull requests merged in 2018-04, with the labels that each got.

#1027 tumor suppressor gene validation adjust
  web/yo/app/scripts/controllers/reportgenerator.js
Labels: curation interface, ready to review

#1025 Map parent OncoTree node
  core/src/main/java/org/mskcc/cbio/oncokb/model/oncotree/TumorType.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/TumorTypeUtils.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/TumorTypeUtilsTest.java
Labels: ready to review

#1026 Do not infer mutation effect based on oncogenicity
  core/src/main/java/org/mskcc/cbio/oncokb/util/MainUtils.java
Labels: ready to review

#985 introduce firebase and integrate with current curation queue code base
  web/yo/app/index.html
  web/yo/app/scripts/app.js
  web/yo/app/scripts/controllers/genes.js
  web/yo/app/scripts/directives/curationQueue.js
  web/yo/app/scripts/factories/VariantFactory.js
  web/yo/app/scripts/services/additionalFile.js
  web/yo/app/scripts/services/importer.js
  web/yo/app/scripts/services/storage.js
  web/yo/app/views/curationQueue.html
  web/yo/bower.json
Labels: Firebase Refactor, curation interface, do not merge
