Repository oncokb/oncokb, pull requests merged in 2018-05, with the labels that each got.

#1046 If there is no common alts, check for alternative alleles
  core/src/main/java/org/mskcc/cbio/oncokb/util/EvidenceUtils.java
Labels: ready to review

#1031 Specify Oncogenicity change in history record
  web/yo/app/scripts/controllers/gene.js
Labels: curation interface, ready to review

#1042 introduce firebase and integrate with current code base
  web/yo/app/data-EXAMPLE/config.json
  web/yo/app/index.html
  web/yo/app/scripts/app.js
  web/yo/app/scripts/controllers/TreeCtrl.js
  web/yo/app/scripts/controllers/gene.js
  web/yo/app/scripts/controllers/genes.js
  web/yo/app/scripts/controllers/nav.js
  web/yo/app/scripts/controllers/tools.js
  web/yo/app/scripts/directives/comments.js
  web/yo/app/scripts/directives/curationQueue.js
  web/yo/app/scripts/directives/driverealtimestring.js
  web/yo/app/scripts/directives/panel.js
  web/yo/app/scripts/directives/realtimestring.js
  web/yo/app/scripts/directives/vusitem.js
  web/yo/app/scripts/factories/VariantFactory.js
  web/yo/app/scripts/services/access.js
  web/yo/app/scripts/services/additionalFile.js
  web/yo/app/scripts/services/databaseconnector.js
  web/yo/app/scripts/services/documents.js
  web/yo/app/scripts/services/importer.js
  web/yo/app/scripts/services/loadfile.js
  web/yo/app/scripts/services/loadfiles.js
  web/yo/app/scripts/services/mainutils.js
  web/yo/app/scripts/services/storage.js
  web/yo/app/scripts/services/stringutils.js
  web/yo/app/scripts/services/user.js
  web/yo/app/scripts/services/users.js
  web/yo/app/styles/main.scss
  web/yo/app/views/comments.html
  web/yo/app/views/curationQueue.html
  web/yo/app/views/gene.html
  web/yo/app/views/genes.html
  web/yo/app/views/modifyTumorTypes.html
  web/yo/app/views/panel.html
  web/yo/app/views/realtimeString.html
  web/yo/app/views/tools.html
  web/yo/app/views/vusItem.html
  web/yo/bower.json
Labels: Firebase Refactor, curation interface
