Repository oncokb/oncokb, pull requests merged in 2018-02, with the labels that each got.

#940 fix the geneStatus issue
  web/yo/app/scripts/controllers/gene.js
  web/yo/app/views/gene.html
Labels: bug, curation interface, rc, ready to review

#944 use last reviewed tumor type names
  web/yo/app/scripts/services/stringutils.js
Labels: bug, curation interface, ready to review

#946 clean up obsolete and red hand related code
  web/yo/app/index.html
  web/yo/app/scripts/controllers/gene.js
  web/yo/app/scripts/controllers/genes.js
  web/yo/app/scripts/controllers/reportgenerator.js
  web/yo/app/scripts/directives/driverealtimestring.js
  web/yo/app/scripts/directives/estatus.js
  web/yo/app/scripts/services/mainutils.js
  web/yo/app/scripts/services/storage.js
  web/yo/app/scripts/services/stringutils.js
  web/yo/app/views/eStatus.html
  web/yo/app/views/reportgenerator.html
Labels: curation interface, ready to review

#953 Improve rc performance
  core/src/main/java/org/mskcc/cbio/oncokb/bo/impl/AlterationBoImpl.java
  core/src/main/java/org/mskcc/cbio/oncokb/bo/impl/EvidenceBoImpl.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/TreatmentDrugId.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/AlterationUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/CacheUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/EvidenceUtils.java
Labels: ready to review

#954 Sort treatment evidence in evidence endpoints
  core/src/main/java/org/mskcc/cbio/oncokb/util/CustomizeComparator.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/EvidenceUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/IndicatorUtils.java
Labels: ready to review

#957 Improve performance based on JProfiler
  core/src/main/java/org/mskcc/cbio/oncokb/bo/AlterationBo.java
  core/src/main/java/org/mskcc/cbio/oncokb/bo/impl/AlterationBoImpl.java
  core/src/main/java/org/mskcc/cbio/oncokb/bo/impl/EvidenceBoImpl.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/AlterationUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/EvidenceUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/TumorTypeUtils.java
Labels: ready to review

#955 Include mutation effect in indicator/search endpoint
  core/src/main/java/org/mskcc/cbio/oncokb/apiModels/Citations.java
  core/src/main/java/org/mskcc/cbio/oncokb/apiModels/MutationEffectResp.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/IndicatorQueryResp.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/IndicatorUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/MainUtils.java
Labels: ready to review

#956 add tools to get reviewed evidences
  web/yo/app/index.html
  web/yo/app/scripts/controllers/reportgenerator.js
  web/yo/app/scripts/factories/VariantFactory.js
  web/yo/app/scripts/services/databaseconnector.js
  web/yo/app/styles/main.scss
  web/yo/app/views/reportgenerator.html
  web/yo/bower.json
Labels: curation interface, enhancement, ready to review

#961 changes based on feedback for query reviewed data
  web/yo/app/scripts/controllers/reportgenerator.js
  web/yo/app/scripts/factories/VariantFactory.js
  web/yo/app/scripts/services/databaseconnector.js
  web/yo/app/styles/main.scss
  web/yo/app/views/reportgenerator.html
Labels: curation interface, enhancement, ready to review

#962 Validate Truncating Mutations Close Issue #918
  web/yo/app/scripts/controllers/reportgenerator.js
  web/yo/app/styles/main.scss
  web/yo/app/views/reportgenerator.html
Labels: curation interface, enhancement, ready to review

#963 Get persistent drug object
  core/src/main/java/org/mskcc/cbio/oncokb/model/TreatmentDrugId.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/CacheUtils.java
Labels: ready to review

#964 bug fix on deletion
  web/yo/app/scripts/controllers/gene.js
Labels: bug, curation interface

#968 Query gene type reviewed data bug fix and remove two old sections in Tools page
  web/yo/app/scripts/controllers/reportgenerator.js
  web/yo/app/views/reportgenerator.html
Labels: curation interface, ready to review
