Repository oncokb/oncokb, pull requests merged in 2022-09, with the labels that each got.

#3252 Allow to specify FDA level for Tx && Allow to exclude cancer types
  .version-level
  core/pom.xml
  core/src/main/java/org/mskcc/cbio/oncokb/Constants.java
  core/src/main/java/org/mskcc/cbio/oncokb/apiModels/FdaAlteration.java
  core/src/main/java/org/mskcc/cbio/oncokb/apiModels/VariantAnnotation.java
  core/src/main/java/org/mskcc/cbio/oncokb/bo/EvidenceBo.java
  core/src/main/java/org/mskcc/cbio/oncokb/bo/impl/EvidenceBoImpl.java
  core/src/main/java/org/mskcc/cbio/oncokb/cache/CacheFetcher.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/ClinicalVariant.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/Evidence.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/GeneNumber.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/IndicatorQueryResp.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/IndicatorQueryTreatment.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/LevelOfEvidence.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/SpecialTumorType.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/EvidenceUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/FdaAlterationUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/IndicatorUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/LevelUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/MainUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/NumberUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/TumorTypeUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/ValidationUtils.java
  core/src/main/resources/migration.sql
  core/src/test/java/org/mskcc/cbio/oncokb/util/FdaParameterizedTest.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/IndicatorUtilsTest.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/TumorTypeUtilsTest.java
  core/src/test/resources/test_cancer_type_treatments.tsv
  core/src/test/resources/test_fda.tsv
  core/src/test/resources/test_tumor_type_summaries.tsv
  core/src/test/resources/test_variant_treatments.tsv
  pom.xml
  web/pom.xml
  web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/LevelsApi.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/LevelsApiController.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/UtilsApiController.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pvt/PrivateUtilsApi.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pvt/PrivateUtilsApiController.java
  web/src/main/java/org/mskcc/cbio/oncokb/controller/DriveAnnotationParser.java
  web/src/main/java/org/mskcc/cbio/oncokb/controller/EvidenceController.java
Labels: feature, database change

#3233 Update docker compose with GN local installation
  README.md
  core/src/main/java/org/mskcc/cbio/oncokb/bo/OncokbTranscriptService.java
  core/src/main/resources/properties-EXAMPLE/config.properties
  docker-compose.yml
Labels: feature

#3264 Add property to update swagger hostname
  core/src/main/resources/properties-EXAMPLE/config.properties
  web/src/main/java/org/mskcc/cbio/oncokb/config/MvcConfigurationPublic.java
Labels: enhancement
