Repository oncokb/oncokb, pull requests merged in 2023-07, with the labels that each got.

#3488 Add an option to send genomicChange through variantAnnotation endpoint
  web/src/main/java/org/mskcc/cbio/oncokb/api/pvt/PrivateUtilsApi.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pvt/PrivateUtilsApiController.java
Labels: enhancement

#3501 Only use allele summary when alternative allele is oncogenic
  core/src/main/java/org/mskcc/cbio/oncokb/util/SummaryUtils.java
  core/src/test/resources/test_tumor_type_summaries.tsv
Labels: fix

#3504 Support genomic change / hgvsg in the search box
  core/src/main/java/org/mskcc/cbio/oncokb/model/TypeaheadQueryType.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/AlterationUtils.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pvt/PrivateSearchApiController.java
Labels: feature

#3481 Support searching by cancer type
  core/src/main/java/org/mskcc/cbio/oncokb/apiModels/CancerTypeMatch.java
  core/src/main/java/org/mskcc/cbio/oncokb/apiModels/DrugMatch.java
  core/src/main/java/org/mskcc/cbio/oncokb/apiModels/LevelsOfEvidenceMatch.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/LevelOfEvidence.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/TypeaheadQueryType.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/TypeaheadSearchResp.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/EvidenceUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/LevelUtils.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pvt/PrivateSearchApiController.java
Labels: feature
