Repository oncokb/oncokb, pull requests merged in 2024-12, with the labels that each got.

#3821 Update swagger specification
  web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/AnnotationsApiController.java
Labels: documentation

#3815 Use both alteration and id to determine the uniqueness of the matched alterations
  core/src/main/java/org/mskcc/cbio/oncokb/util/AlterationUtils.java
Labels: fix

#3823 Add error handlers to provide proper API code
  web/src/main/java/org/mskcc/cbio/oncokb/controller/advice/ApiHttpErrorExceptionHandler.java
  web/src/main/java/org/mskcc/cbio/oncokb/controller/advice/ExceptionTranslator.java
Labels: fix

#3826 Do no trim out newline characters in descriptions
  core/src/main/java/org/mskcc/cbio/oncokb/util/CplUtils.java
Labels: enhancement
