Repository oncokb/oncokb, pull requests merged in 2024-07, with the labels that each got.

#3747 Bump spring version to implicitly support HEAD
  core/src/main/java/org/mskcc/cbio/oncokb/cache/CustomRedisCache.java
  pom.xml
Labels: enhancement

#3756 Concert three letter AA to one letter AA
  core/src/main/java/org/mskcc/cbio/oncokb/model/Alteration.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/Query.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/AminoAcidConverterUtils.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/AminoAcidConverterUtilsTest.java
Labels: feature

#3762 Fix tumor type summary mapping
  core/src/main/java/org/mskcc/cbio/oncokb/bo/impl/EvidenceBoImpl.java
  core/src/test/resources/test_tumor_type_summaries.tsv
Labels: fix

#3759 Improve frameshift variant parse
  core/src/main/java/org/mskcc/cbio/oncokb/Constants.java
  core/src/main/java/org/mskcc/cbio/oncokb/bo/AlterationBo.java
  core/src/main/java/org/mskcc/cbio/oncokb/bo/impl/AlterationBoImpl.java
  core/src/main/java/org/mskcc/cbio/oncokb/importer/MapPortalAlteration.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/FrameshiftVariant.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/AlterationUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/IndicatorUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/VariantConsequenceUtils.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/AlterationUtilsTest.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/AnnotateAlterationTest.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/FindRelevantAlterationsTest.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/GenomeNexusUtilsTest.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/VariantConsequenceUtilsTest.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/VariantsApiController.java
Labels: enhancement

#3764 Stop codon frameshift alt should not be considered as truncating
  core/src/main/java/org/mskcc/cbio/oncokb/bo/impl/AlterationBoImpl.java
  core/src/main/java/org/mskcc/cbio/oncokb/model/StructuralAlteration.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/AlterationUtils.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/AlterationUtilsTest.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/FindRelevantAlterationsTest.java
  web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/ClassificationApiController.java
Labels: fix
