Repository oncokb/oncokb, pull requests merged in 2024-09, with the labels that each got.

#3787 Do not include the for plural mutations in mutation summary
  core/src/main/java/org/mskcc/cbio/oncokb/util/SummaryUtils.java
  core/src/test/resources/test_tumor_type_summaries.tsv
  core/src/test/resources/test_variant_summaries.tsv
Labels: fix

#3786 Parse mutation summary
  web/src/main/java/org/mskcc/cbio/oncokb/controller/DriveAnnotationParser.java
Labels: enhancement

#3788 Update alteration name conversion logics
  core/src/main/java/org/mskcc/cbio/oncokb/util/MainUtils.java
  core/src/main/java/org/mskcc/cbio/oncokb/util/SummaryUtils.java
  core/src/test/java/org/mskcc/cbio/oncokb/util/MainUtilsTest.java
Labels: fix

#3789 Update unit tests for v4.21
  core/src/test/resources/test_structural_variants.tsv
  core/src/test/resources/test_tumor_type_summaries.tsv
Labels: feature
